feat: add greedy whitespace tokenizer
conventional-commits/parser pull request #25
Opened 2020-12-25 14:38 UTC by byCedric

Building on top of #24, using the same greedy principle as `whitespace` nodes.

<img width="400" alt="Screenshot 2020-12-25 at 15 34 14" src="https://user-images.githubusercontent.com/1203991/103137189-06b69f80-46c7-11eb-80ea-b4c39a2446cb.png">

It's still a draft, at least until we decided to merge or change #24. Also running into this issue where we trim the outer newlines/whitespaces. Might be better to either not-do that, to maintain positioning within the raw input.

<img width="400" alt="Screenshot 2020-12-25 at 15 38 15" src="https://user-images.githubusercontent.com/1203991/103137213-35cd1100-46c7-11eb-8246-1e5088818c3e.png">

2020-12-25 23:08 UTC, bcoe commented
@byCedric in general this looks great to me.

One question it begs, is do we consider footers part of the `body`, where this complicates things a bit is that we end up with the `<newline>` token between the body and first footer.

Thinking out loud, how hard would it be to pull the <footer> and dividing <newline> up to the same level as <message>.

2020-12-25 23:26 UTC, bcoe commented
It's a little bit uglier of a grammar, but does this get the point across and give a better tree structure?

```ebnf
<message>       ::= <summary>, <newline>*, <body>, <newline>*, <footer>*
                 |  <summary>

<body>          ::= <any text except footer*>, <newline>, <body>
                 | <any text except footer*>
```

2020-12-25 23:41 UTC, byCedric commented
> It's a little bit uglier of a grammar, but does this get the point across and give a better tree structure?
> 
> ```ebnf
> <message>       ::= <summary>, <newline>*, <body>, <newline>*, <footer>*
>                  |  <summary>
> 
> <body>          ::= <any text except footer*>, <newline>, <body>
>                  | <any text except footer*>
> ```

Yes, I think so! Although I think we need to use the `+` instead of `*` here. If there is no newline, it's part of the `summary.text`. Same for the footer, if there is no newline there it's parsed as the body.

Both `footer` and `body` are optional, maybe something like this? I'm not too familiar with (e)BNF structures.

```
<message ::= <summary> [<newline>+, <body>], [<newline>+ <footer>]
```

2020-12-26 00:30 UTC, bcoe commented
@byCedric what about:

```
<message ::= <summary> [<newline>+, <body>], [<newline> <footer>+]

<body>   ::= <any text except newline or footer+>, <newline>, <body>
                 | <any text except newline or footer+>

<footer>        ::= <token>, <separator>, <whitespace>*, <value>, [<newline>]
```

should we do this in a separate PR.

2020-12-27 16:26 UTC, byCedric commented
> @byCedric what about:
> 
> ```
> <message ::= <summary> [<newline>+, <body>], [<newline> <footer>+]
> 
> <body>   ::= <any text except newline or footer+>, <newline>, <body>
>                  | <any text except newline or footer+>
> 
> <footer>        ::= <token>, <separator>, <whitespace>*, <value>, [<newline>]
> ```
> 
> should we do this in a separate PR.

Just to double check if I understand what you mean @bcoe, you prefer something like this right?
![Screenshot 2020-12-27 at 17 26 13](https://user-images.githubusercontent.com/1203991/103175233-b5461600-4868-11eb-8bea-ae646ace307a.png)

2020-12-27 22:50 UTC, bcoe commented
> Just to double check if I understand what you mean @bcoe, you prefer something like this right?

I think we're pretty much on the same page conceptually, I opened up #26 as a potential approach.

> Not sure if I did the body text right here, or if we should leave them as empty "" text nodes.

The problem with including the `\n` in the `text` nodes is that we define the next nodes as:

```
<any UTF8-octets except newline>*
```

i.e., they explicitly don't contain a `newline`. Could we just add a note for implementers that the original `body` can be by joining with `\n`?

2020-12-29 18:38 UTC, bcoe approved these changes

2020-12-29 21:13 UTC, wesleytodd approved these changes
Nothing to add for me, but I am following along on the other conversations which I think are good to figure out.

As for adding a note that you need to add a newline which would not be represented in the tree, I think this is not a desirable solution.  I also think that we should not say "anything but a new line" and also, "you need to add a new line".  So I am not sure where I land on this yet.

2020-12-31 14:21 UTC, byCedric commented
@bcoe @wesleytodd I just updated the PR to include the latest `main`. Because of some weird/complex merge conflicts, I opted for a reimplementation. Right now it parses commits like the image below. In a follow-up PR, I'll implement @bcoe's suggestion to pull `newline` from `footer` and put in in the tree as sibling (as children of `message`).

I agree with your comments about concatenating the newlines in `text`, but with the current state people can easily merge the body back to a string with:

```
const tree = parser(<message>)
const body = tree.children.find(node => node.type === 'body')

// this will join `<text>` and `<newline>*` together without handling newline or text node types
const text = body.children.map(node => node.value).join('') 
```

**Current state of newlines**
<img width="400" alt="Screenshot 2020-12-31 at 15 17 09" src="https://user-images.githubusercontent.com/1203991/103413790-4247e280-4b7b-11eb-987a-eb930cbbc68a.png">

2021-01-05 17:52 UTC, bcoe requested changes
nit: in the grammar in the README, there are a few places where we have `<newline>`, I think this should always be `<newline>+`, or `<newline>*`, depending on whether it's optional.

2021-01-05 20:08 UTC, bcoe approved these changes

2021-01-07 00:31 UTC, merged